FROM node:14-alpine as builder

WORKDIR /capstone_deploy/frontend

ENV PATH /capstone_deploy/frontend/node_modules/.bin:${PATH}

COPY /package.json /capstone_deploy/frontend/package.json
RUN npm install

COPY . /capstone_deploy/frontend
RUN npm run-script build

FROM nginx

RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

# 위에서 생성한 앱의 빌드산출물을 nginx의 샘플 앱이 사용하던 폴더로 이동
COPY --from=builder /capstone_deploy/frontend/build /usr/share/nginx/html
COPY /etc/letsencrypt /etc

# 80포트 오픈하고 nginx 실행
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
